package com.ai.openai.controller;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * REST API controller for handling chat interactions with multiple AI models.
 *
 * This controller provides endpoints to communicate with different AI chat models:
 * - OpenAI: For OpenAI's GPT models
 * - DeepSeek: For DeepSeek's chat models
 *
 * All endpoints are prefixed with {@code /api} and accept user messages as query parameters.
 *
 * @author Anuja Singh
 * @version 1.0
 */
@RestController
@RequestMapping("/api")
public class ChatController {

    /** ChatClient instance configured for OpenAI models */
    private final ChatClient openAiChatClient;

    /** ChatClient instance configured for DeepSeek models */
    private final ChatClient deepSeekChatClient;

    /**
     * Constructs a ChatController with OpenAI and DeepSeek chat clients.
     *
     * Both chat clients are injected via constructor dependency injection with
     * specific qualifiers to distinguish between the two implementations.
     *
     * @param openAiChatClient the ChatClient bean configured for OpenAI models,
     *                         identified by the qualifier "openAiChatClient"
     * @param deepSeekChatClient the ChatClient bean configured for DeepSeek models,
     *                           identified by the qualifier "deepSeekChatClient"
     */
    public ChatController(@Qualifier("openAiChatClient") ChatClient openAiChatClient,
                          @Qualifier("deepSeekChatClient") ChatClient deepSeekChatClient) {
        this.openAiChatClient = openAiChatClient;
        this.deepSeekChatClient = deepSeekChatClient;
    }

    /**
     * Sends a chat message to the OpenAI model and retrieves the response.
     *
     * Endpoint: {@code GET /api/openAi/chat}
     *
     * @param message the user's message to be processed by the OpenAI chat model.
     *                This parameter is required and must be provided as a query parameter.
     * @return the response content generated by the OpenAI chat model
     *
     * @example
     * GET /api/openAi/chat?message=Hello%20OpenAI
     * Response: "Hello! How can I assist you today?"
     */
    @GetMapping("/openAi/chat")
    public String OpenAiChat(@RequestParam(value = "message") String message) {
        return openAiChatClient.prompt()
                .user(message)
                .call()
                .content();
    }

    /**
     * Sends a chat message to the DeepSeek model and retrieves the response.
     *
     * Endpoint: {@code GET /api/deepSeek/chat}
     *
     * @param message the user's message to be processed by the DeepSeek chat model.
     *                This parameter is required and must be provided as a query parameter.
     * @return the response content generated by the DeepSeek chat model
     *
     * @example
     * GET /api/deepSeek/chat?message=Hello%20DeepSeek
     * Response: "Hi there! What can I help you with?"
     */
    @GetMapping("/deepSeek/chat")
    public String DeepSeekchat(@RequestParam(value = "message") String message) {
        return deepSeekChatClient.prompt()
                .user(message)
                .call()
                .content();
    }

}
